version: '3'

tasks:
  production:build:
    desc: Build frontend and copy to backend/static
    dir: backend
    cmds:
      - ./build.sh

  production:pack:
    desc: Build and package as larpadmin.zip
    cmds:
      - ./pack.sh

  production:backend:
    deps:
      - build
    desc: Run backend dev server in production mode
    dir: backend
    cmds:
      - ENVIRONMENT=production gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8001

  production:migrate:
    desc: Run database migrations on production
    dir: backend
    cmds:
      - ENVIRONMENT=production alembic upgrade head

  dev:backend:
    desc: Run backend dev server
    dir: backend
    cmds:
      - uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  dev:frontend:
    desc: Run frontend dev server
    dir: frontend
    cmds:
      - npm run dev

  dev:migrate:
    desc: Run database migrations
    dir: backend
    cmds:
      - alembic upgrade head

  test:
    desc: Run backend tests
    dir: backend
    cmds:
      - pytest
