"""add session_id and npc_response to dialogue_log

Revision ID: 2356bde222ec
Revises: 01d0cd4d6b90
Create Date: 2025-11-24 23:00:18.080964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2356bde222ec'
down_revision: Union[str, None] = '01d0cd4d6b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogue_logs', sa.Column('session_id', sa.String(length=64), nullable=False, comment='Session identifier for grouping related dialogue logs'))
    op.add_column('dialogue_logs', sa.Column('npc_response', sa.Text(), nullable=True, comment='NPC response to the player message'))
    op.create_index(op.f('ix_dialogue_logs_session_id'), 'dialogue_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_logs_session_id'), table_name='dialogue_logs')
    op.drop_column('dialogue_logs', 'npc_response')
    op.drop_column('dialogue_logs', 'session_id')
    # ### end Alembic commands ###
