"""initial_migration

Revision ID: 813a24a50f35
Revises: 
Create Date: 2025-11-24 20:30:06.841056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '813a24a50f35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_implementations',
    sa.Column('id', sa.String(length=64), nullable=False, comment="Algorithm ID like 'keyword_v1', 'embedding_v2'"),
    sa.Column('type', sa.Enum('keyword', 'embedding', 'hybrid', 'llm_rerank', name='algorithm_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('doc_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('available', 'deprecated', name='algorithm_impl_status'), nullable=False),
    sa.Column('param_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON Schema for parameter validation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debug_audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level', sa.Enum('debug', 'info', 'warn', 'error', name='log_level'), nullable=False, comment='Log level: debug, info, warn, error'),
    sa.Column('source', sa.String(length=255), nullable=False, comment='Source of the log (e.g., module name, endpoint)'),
    sa.Column('message', sa.Text(), nullable=False, comment='Log message'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Additional context data (request params, stack trace, etc.)'),
    sa.Column('request_id', sa.String(length=255), nullable=True, comment='Request ID for tracing'),
    sa.Column('user_id', sa.String(length=255), nullable=True, comment='User ID if applicable'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debug_audit_logs_created_at'), 'debug_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_debug_audit_logs_level'), 'debug_audit_logs', ['level'], unique=False)
    op.create_index(op.f('ix_debug_audit_logs_request_id'), 'debug_audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_debug_audit_logs_source'), 'debug_audit_logs', ['source'], unique=False)
    op.create_index(op.f('ix_debug_audit_logs_user_id'), 'debug_audit_logs', ['user_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('system', 'npc_dialog', 'clue_explain', name='template_type'), nullable=False),
    sa.Column('scope_type', sa.Enum('global', 'script', 'npc', name='template_scope_type'), nullable=False),
    sa.Column('scope_target_id', sa.UUID(as_uuid=False), nullable=True, comment='Target ID for script/npc scope'),
    sa.Column('content', sa.Text(), nullable=False, comment='Template content with {var} placeholders'),
    sa.Column('variables_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Metadata about used variables for validation'),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='template_status'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Script title'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Brief summary of the script story'),
    sa.Column('background', sa.Text(), nullable=True, comment='Background setting and context for the story'),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='script_difficulty'), nullable=False),
    sa.Column('truth', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The truth of the case: murderer, weapon, motive, crime_method'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_deleted_at'), 'scripts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_scripts_title'), 'scripts', ['title'], unique=False)
    op.create_table('algorithm_strategies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impl_id', sa.String(length=64), nullable=False),
    sa.Column('scope_type', sa.Enum('global', 'script', 'scene', 'npc', name='strategy_scope_type'), nullable=False),
    sa.Column('scope_target_id', sa.UUID(as_uuid=False), nullable=True, comment='Target ID for script/scene/npc scope'),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Algorithm parameters'),
    sa.Column('status', sa.Enum('draft', 'published', 'deprecated', name='strategy_status'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['impl_id'], ['algorithm_implementations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_algorithm_strategies_impl_id'), 'algorithm_strategies', ['impl_id'], unique=False)
    op.create_table('npcs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('script_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True, comment='NPC background story'),
    sa.Column('personality', sa.Text(), nullable=True, comment='NPC personality traits'),
    sa.Column('knowledge_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='NPC knowledge scope: knows, does_not_know, world_model_limits'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npcs_script_id'), 'npcs', ['script_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('script_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scene_type', sa.Enum('investigation', 'interrogation', 'free_dialogue', name='scene_type'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_script_id'), 'scenes', ['script_id'], unique=False)
    op.create_table('clues',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('script_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('npc_id', sa.UUID(as_uuid=False), nullable=False, comment='The NPC who knows this clue'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Clue name/title'),
    sa.Column('type', sa.Enum('text', 'image', name='clue_type'), nullable=False, comment='Content type: text or image'),
    sa.Column('detail', sa.Text(), nullable=False, comment='The clue content itself (线索本身)'),
    sa.Column('detail_for_npc', sa.Text(), nullable=False, comment='Guidance for NPC on how to reveal this clue (指导 NPC 回答这条线索时需要说的话)'),
    sa.Column('trigger_keywords', postgresql.ARRAY(sa.String()), nullable=False, comment='Keywords for vector match'),
    sa.Column('trigger_semantic_summary', sa.Text(), nullable=False, comment='Semantic summary for vector match'),
    sa.Column('prereq_clue_ids', postgresql.ARRAY(sa.UUID(as_uuid=False)), nullable=False, comment='Prerequisite clue IDs (前置线索)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clues_npc_id'), 'clues', ['npc_id'], unique=False)
    op.create_index(op.f('ix_clues_script_id'), 'clues', ['script_id'], unique=False)
    op.create_table('dialogue_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('script_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scene_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('npc_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('player_message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Current state and unlocked clues'),
    sa.Column('strategy_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('matched_clues', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='All matched clues with scores'),
    sa.Column('triggered_clues', postgresql.ARRAY(sa.UUID(as_uuid=False)), nullable=False, comment='Final triggered clue IDs'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['algorithm_strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_logs_created_at'), 'dialogue_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_dialogue_logs_npc_id'), 'dialogue_logs', ['npc_id'], unique=False)
    op.create_index(op.f('ix_dialogue_logs_scene_id'), 'dialogue_logs', ['scene_id'], unique=False)
    op.create_index(op.f('ix_dialogue_logs_script_id'), 'dialogue_logs', ['script_id'], unique=False)
    op.create_index(op.f('ix_dialogue_logs_strategy_id'), 'dialogue_logs', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_logs_strategy_id'), table_name='dialogue_logs')
    op.drop_index(op.f('ix_dialogue_logs_script_id'), table_name='dialogue_logs')
    op.drop_index(op.f('ix_dialogue_logs_scene_id'), table_name='dialogue_logs')
    op.drop_index(op.f('ix_dialogue_logs_npc_id'), table_name='dialogue_logs')
    op.drop_index(op.f('ix_dialogue_logs_created_at'), table_name='dialogue_logs')
    op.drop_table('dialogue_logs')
    op.drop_index(op.f('ix_clues_script_id'), table_name='clues')
    op.drop_index(op.f('ix_clues_npc_id'), table_name='clues')
    op.drop_table('clues')
    op.drop_index(op.f('ix_scenes_script_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_npcs_script_id'), table_name='npcs')
    op.drop_table('npcs')
    op.drop_index(op.f('ix_algorithm_strategies_impl_id'), table_name='algorithm_strategies')
    op.drop_table('algorithm_strategies')
    op.drop_index(op.f('ix_scripts_title'), table_name='scripts')
    op.drop_index(op.f('ix_scripts_deleted_at'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_debug_audit_logs_user_id'), table_name='debug_audit_logs')
    op.drop_index(op.f('ix_debug_audit_logs_source'), table_name='debug_audit_logs')
    op.drop_index(op.f('ix_debug_audit_logs_request_id'), table_name='debug_audit_logs')
    op.drop_index(op.f('ix_debug_audit_logs_level'), table_name='debug_audit_logs')
    op.drop_index(op.f('ix_debug_audit_logs_created_at'), table_name='debug_audit_logs')
    op.drop_table('debug_audit_logs')
    op.drop_table('algorithm_implementations')
    # ### end Alembic commands ###
