"""add_llm_configs_table

Revision ID: 9adf9aa2f35b
Revises: 2962c4569553
Create Date: 2025-11-24 21:48:12.274163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9adf9aa2f35b'
down_revision: Union[str, None] = '2962c4569553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_configs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name for this configuration'),
    sa.Column('type', sa.Enum('embedding', 'chat', name='llm_config_type'), nullable=False, comment='Configuration type: embedding or chat'),
    sa.Column('model', sa.String(length=255), nullable=False, comment='Model name (e.g., text-embedding-ada-002, gpt-4)'),
    sa.Column('base_url', sa.String(length=512), nullable=False, comment='API base URL'),
    sa.Column('api_key', sa.Text(), nullable=False, comment='API key (should be encrypted in production)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Whether this is the default config for its type'),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Type-specific options: embedding (similarity_threshold, dimensions) or chat (temperature, max_tokens, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_configs_deleted_at'), 'llm_configs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_llm_configs_is_default'), 'llm_configs', ['is_default'], unique=False)
    op.create_index(op.f('ix_llm_configs_name'), 'llm_configs', ['name'], unique=False)
    op.create_index(op.f('ix_llm_configs_type'), 'llm_configs', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_configs_type'), table_name='llm_configs')
    op.drop_index(op.f('ix_llm_configs_name'), table_name='llm_configs')
    op.drop_index(op.f('ix_llm_configs_is_default'), table_name='llm_configs')
    op.drop_index(op.f('ix_llm_configs_deleted_at'), table_name='llm_configs')
    op.drop_table('llm_configs')
    # ### end Alembic commands ###
