"""add_prompt_templates_table

Revision ID: acbf0b5fb934
Revises: 001
Create Date: 2025-11-23 21:23:09.963644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acbf0b5fb934'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('system', 'npc_dialog', 'clue_explain', name='template_type'), nullable=False),
    sa.Column('scope_type', sa.Enum('global', 'script', 'npc', name='template_scope_type'), nullable=False),
    sa.Column('scope_target_id', sa.UUID(as_uuid=False), nullable=True, comment='Target ID for script/npc scope'),
    sa.Column('content', sa.Text(), nullable=False, comment='Template content with {var} placeholders'),
    sa.Column('variables_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Metadata about used variables for validation'),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='template_status'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('algorithm_implementations', 'id',
               existing_type=sa.VARCHAR(length=64),
               comment="Algorithm ID like 'keyword_v1', 'embedding_v2'",
               existing_nullable=False)
    op.alter_column('algorithm_implementations', 'param_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON Schema for parameter validation',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('algorithm_strategies', 'scope_target_id',
               existing_type=sa.UUID(),
               comment='Target ID for script/scene/npc scope',
               existing_nullable=True)
    op.alter_column('algorithm_strategies', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Algorithm parameters',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('clues', 'title_internal',
               existing_type=sa.VARCHAR(length=255),
               comment='Internal title for designers',
               existing_nullable=False)
    op.alter_column('clues', 'title_player',
               existing_type=sa.VARCHAR(length=255),
               comment='Title shown to players',
               existing_nullable=False)
    op.alter_column('clues', 'content_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Additional content data (images, structured content)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('clues', 'stage',
               existing_type=sa.INTEGER(),
               comment='Story stage this clue belongs to',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('clues', 'npc_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment='Related NPC IDs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::uuid[]"))
    op.alter_column('clues', 'unlock_conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Conditions to unlock this clue',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('clues', 'effects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Effects when clue is triggered',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('clues', 'one_time',
               existing_type=sa.BOOLEAN(),
               comment='Whether clue can only be triggered once',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('dialogue_logs', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Current state and unlocked clues',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dialogue_logs', 'matched_clues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='All matched clues with scores',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dialogue_logs', 'triggered_clues',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment='Final triggered clue IDs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::uuid[]"))
    op.alter_column('npcs', 'relations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Relationships with other NPCs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('scripts', 'expected_duration',
               existing_type=sa.INTEGER(),
               comment='Expected duration in minutes',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scripts', 'expected_duration',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Expected duration in minutes',
               existing_nullable=True)
    op.alter_column('npcs', 'relations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Relationships with other NPCs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dialogue_logs', 'triggered_clues',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment=None,
               existing_comment='Final triggered clue IDs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::uuid[]"))
    op.alter_column('dialogue_logs', 'matched_clues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='All matched clues with scores',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('dialogue_logs', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Current state and unlocked clues',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('clues', 'one_time',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether clue can only be triggered once',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('clues', 'effects',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Effects when clue is triggered',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('clues', 'unlock_conditions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Conditions to unlock this clue',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('clues', 'npc_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               comment=None,
               existing_comment='Related NPC IDs',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::uuid[]"))
    op.alter_column('clues', 'stage',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Story stage this clue belongs to',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('clues', 'content_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Additional content data (images, structured content)',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('clues', 'title_player',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Title shown to players',
               existing_nullable=False)
    op.alter_column('clues', 'title_internal',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Internal title for designers',
               existing_nullable=False)
    op.alter_column('algorithm_strategies', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Algorithm parameters',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('algorithm_strategies', 'scope_target_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Target ID for script/scene/npc scope',
               existing_nullable=True)
    op.alter_column('algorithm_implementations', 'param_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON Schema for parameter validation',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('algorithm_implementations', 'id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment="Algorithm ID like 'keyword_v1', 'embedding_v2'",
               existing_nullable=False)
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
