"""Schemas for AI Story Creation Assistant."""

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class StoryGenre(str, Enum):
    """Story genre types."""

    MURDER_MYSTERY = "murder_mystery"  # 谋杀推理
    THRILLER = "thriller"  # 悬疑惊悚
    WUXIA = "wuxia"  # 武侠
    MODERN = "modern"  # 现代都市
    HISTORICAL = "historical"  # 历史
    FANTASY = "fantasy"  # 奇幻


class GenerationStep(str, Enum):
    """Story generation step."""

    SETTING = "setting"  # 故事设定
    TRUTH = "truth"  # 真相设计
    CLUE_CHAIN = "clue_chain"  # 线索链
    NPC_ASSIGNMENT = "npc_assignment"  # NPC分配
    DETAIL_FILL = "detail_fill"  # 细节填充
    REVIEW = "review"  # 审核确认


class ClueImportance(str, Enum):
    """Clue importance level."""

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


# ========== Step 1: Story Setting ==========


class StorySettingInput(BaseModel):
    """Step 1: Story setting input."""

    genre: StoryGenre = Field(..., description="Story genre type")
    era: str = Field(..., description="Era/time period, e.g., '1920s Shanghai'")
    location: str = Field(..., description="Main location, e.g., 'A mansion in the French Concession'")
    atmosphere: str | None = Field(None, description="Atmosphere description")
    npc_count: int = Field(default=6, ge=3, le=12, description="Number of NPCs")
    additional_notes: str | None = Field(None, description="Additional requirements or notes")


class StorySettingResponse(BaseModel):
    """Response for story setting generation."""

    setting: StorySettingInput
    ai_suggestions: list[str] = Field(default_factory=list)
    ready_for_next: bool = True


# ========== Step 2: Truth Design ==========


class TruthInput(BaseModel):
    """Step 2: Truth input (partial input, AI can complete)."""

    murderer_hint: str | None = Field(None, description="Murderer hint/characteristics")
    motive_hint: str | None = Field(None, description="Motive hint")
    method_hint: str | None = Field(None, description="Method/weapon hint")
    auto_generate: bool = Field(default=False, description="Let AI auto-generate")


class TruthOption(BaseModel):
    """A single truth option generated by AI."""

    murderer: str = Field(..., description="The murderer identity")
    motive: str = Field(..., description="The motive for the crime")
    method: str = Field(..., description="The method/weapon used")
    twist: str | None = Field(None, description="Optional plot twist")
    summary: str = Field(..., description="Brief summary of this option")


class TruthOptionsResponse(BaseModel):
    """Response containing multiple truth options."""

    options: list[TruthOption]
    recommendation_index: int = Field(default=0, description="Recommended option index")
    recommendation_reason: str | None = None


class SelectedTruth(BaseModel):
    """User selected/confirmed truth."""

    murderer: str
    motive: str
    method: str
    twist: str | None = None


# ========== Step 3: Clue Chain Design ==========


class ClueNode(BaseModel):
    """A node in the clue chain."""

    temp_id: str = Field(..., description="Temporary ID for this session")
    name: str = Field(..., description="Clue name")
    importance: ClueImportance = Field(..., description="Importance level")
    description: str = Field(..., description="Brief description of the clue")
    reasoning_role: str = Field(..., description="Role in the reasoning process")
    prereq_temp_ids: list[str] = Field(default_factory=list, description="Prerequisite clue temp IDs")
    suggested_npc_role: str | None = Field(None, description="Suggested NPC role to hold this clue")


class ClueEdge(BaseModel):
    """An edge in the clue chain graph."""

    source: str = Field(..., description="Source clue temp_id (prerequisite)")
    target: str = Field(..., description="Target clue temp_id (dependent)")


class ClueChainValidation(BaseModel):
    """Validation result for clue chain."""

    is_valid: bool = True
    has_cycles: bool = False
    cycles: list[list[str]] = Field(default_factory=list)
    unreachable_clues: list[str] = Field(default_factory=list)
    root_clue_count: int = 0
    reasoning_path_count: int = 0
    warnings: list[str] = Field(default_factory=list)


class ClueChainSuggestion(BaseModel):
    """AI generated clue chain suggestion."""

    nodes: list[ClueNode]
    edges: list[ClueEdge]
    reasoning_paths: list[list[str]] = Field(default_factory=list, description="Key reasoning paths")
    validation: ClueChainValidation
    ai_notes: list[str] = Field(default_factory=list, description="AI suggestions and notes")


class ClueChainAdjustment(BaseModel):
    """User adjustment to clue chain."""

    action: str = Field(..., description="Action type: add, remove, modify, add_edge, remove_edge")
    clue_temp_id: str | None = None
    clue_data: ClueNode | None = None
    edge_data: ClueEdge | None = None


class ClueChainInput(BaseModel):
    """Step 3: Clue chain input."""

    adjustments: list[ClueChainAdjustment] | None = None
    regenerate: bool = False
    optimization_focus: str | None = Field(None, description="Focus for AI optimization")


# ========== Step 4: NPC Assignment ==========


class NPCKnowledgeScopePreview(BaseModel):
    """Preview of NPC knowledge scope."""

    knows: list[str] = Field(default_factory=list)
    does_not_know: list[str] = Field(default_factory=list)
    world_model_limits: list[str] = Field(default_factory=list)


class NPCSuggestion(BaseModel):
    """AI suggested NPC."""

    temp_id: str = Field(..., description="Temporary ID for this session")
    name: str = Field(..., description="NPC name")
    role: str = Field(..., description="NPC role/identity")
    age: int | None = None
    background_summary: str = Field(..., description="Brief background")
    personality_traits: list[str] = Field(default_factory=list)
    assigned_clue_temp_ids: list[str] = Field(default_factory=list, description="Assigned clue temp IDs")
    knowledge_scope_preview: NPCKnowledgeScopePreview = Field(default_factory=NPCKnowledgeScopePreview)


class NPCAssignmentInput(BaseModel):
    """Step 4: NPC assignment input."""

    npc_count: int = Field(default=6, ge=3, le=12)
    custom_npcs: list[NPCSuggestion] | None = None
    auto_assign: bool = True
    reassign_clues: bool = False


class NPCAssignmentResponse(BaseModel):
    """Response for NPC assignment."""

    npcs: list[NPCSuggestion]
    unassigned_clue_temp_ids: list[str] = Field(default_factory=list)
    ai_notes: list[str] = Field(default_factory=list)


# ========== Step 5: Detail Generation ==========


class ClueDetailRequest(BaseModel):
    """Request to generate details for a specific clue."""

    clue_temp_id: str
    regenerate: bool = False


class ClueDetail(BaseModel):
    """Detailed clue content."""

    temp_id: str
    name: str
    detail: str = Field(..., description="The actual clue content")
    detail_for_npc: str = Field(..., description="NPC guidance on revealing this clue")
    trigger_keywords: list[str] = Field(default_factory=list)
    trigger_semantic_summary: str = Field(..., description="Semantic summary for matching")


class NPCDetail(BaseModel):
    """Detailed NPC content."""

    temp_id: str
    name: str
    age: int | None
    background: str
    personality: str
    knowledge_scope: NPCKnowledgeScopePreview


class DetailFillResponse(BaseModel):
    """Response for detail generation."""

    clue_details: list[ClueDetail] = Field(default_factory=list)
    npc_details: list[NPCDetail] = Field(default_factory=list)
    progress: float = Field(ge=0.0, le=1.0, description="Generation progress 0-1")


# ========== Final Story Draft ==========


class StoryDraft(BaseModel):
    """Complete story draft ready for creation."""

    # Story setting
    title: str
    summary: str
    background: str
    difficulty: str = "medium"

    # Truth
    truth: dict[str, Any]

    # Clue chain
    clue_chain: ClueChainSuggestion

    # NPCs with clues
    npcs: list[NPCSuggestion]

    # Detailed content
    clue_details: list[ClueDetail]
    npc_details: list[NPCDetail]

    # Validation
    validation_result: ClueChainValidation
    ready_to_create: bool = False


# ========== Session State ==========


class AIAssistantSession(BaseModel):
    """Session state for AI story creation."""

    session_id: str
    current_step: GenerationStep = GenerationStep.SETTING
    setting: StorySettingInput | None = None
    selected_truth: SelectedTruth | None = None
    clue_chain: ClueChainSuggestion | None = None
    npcs: list[NPCSuggestion] | None = None
    clue_details: list[ClueDetail] | None = None
    npc_details: list[NPCDetail] | None = None
    created_at: str
    updated_at: str


# ========== API Request/Response ==========


class GenerateTruthRequest(BaseModel):
    """Request to generate truth options."""

    setting: StorySettingInput
    hints: TruthInput | None = None
    llm_config_id: str | None = None


class GenerateClueChainRequest(BaseModel):
    """Request to generate clue chain."""

    setting: StorySettingInput
    truth: SelectedTruth
    existing_chain: ClueChainSuggestion | None = None
    adjustments: list[ClueChainAdjustment] | None = None
    llm_config_id: str | None = None


class GenerateNPCsRequest(BaseModel):
    """Request to generate NPCs."""

    setting: StorySettingInput
    truth: SelectedTruth
    clue_chain: ClueChainSuggestion
    npc_count: int = 6
    llm_config_id: str | None = None


class GenerateDetailsRequest(BaseModel):
    """Request to generate details."""

    setting: StorySettingInput
    truth: SelectedTruth
    clue_chain: ClueChainSuggestion
    npcs: list[NPCSuggestion]
    clue_temp_ids: list[str] | None = None  # If None, generate all
    llm_config_id: str | None = None


class CreateScriptFromDraftRequest(BaseModel):
    """Request to create actual script from draft."""

    draft: StoryDraft


class OptimizeClueChainRequest(BaseModel):
    """Request to optimize clue chain."""

    clue_chain: ClueChainSuggestion
    focus: str | None = Field(None, description="Optimization focus: redundancy, accessibility, balance")
    llm_config_id: str | None = None
